name: Build Nuxt
on:
  push:
    branches:
      - master

  build_vue:
    runs-on: ubuntu-latest
    name: Build Nuxt
    steps:
      - uses: actions/checkout@v2
      - id: Build-Vue
        uses: ashkantaravati/NuxtToGithubPages@v1.0
        with:
          username: "larsvdniet"
          reponame: "dinnerwalks-nuxtjs"
          token: ${{ secrets.GITHUB_TOKEN }}
