name: Deployed to Beta Environment
on:
  push:
    # Negeer commits die zijn gemaakt in:
    paths-ignore:
      - '.github/**'
      - 'extra/**'
      - 'README.md'
      - LICENSE
    # De branch waarop het getriggerd wordt
    branches:
      - main
jobs:
  deploy:
    name: Deploy to Beta
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v1
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install npm dependencies
        run: npm install
      - name: Run build task
        run: npm run build --if-present
      - name: Create .env file
        run: 'echo "$ENV_FILE" > .env'
        shell: bash
        env:
          ENV_FILE: ${{secrets.DOT_ENV}}
        working-directory: ./src

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          EXCLUDE: "/dist/, /node_modules/" 